[ERRORS] Misspell property on inferred argument
Typescript can infer many things (but not all) just based on usage and
surrounding context. Notice how it infers the type of `session` in the
function passed to `map`. Use this to limit the amount of work you need
to do.

dashboard.tsx:16:24 - error TS2551: Property 'sesion' does not exist on type 'DashboardSession'. Did you mean 'session'?

16       <li key={session.sesion.id}>
                          ~~~~~~